### ISSUE TITLE
Add 50X error page

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/frontend-template#5]
### Explication
Add the view for the 50X error. The user will be redirected to this view when requesting an error occurs
### Checklist

- [ ] Add a error 50X route at React Router
- [ ] Add a empty or basic file to the 50X view

**Comment by arodriguezl9302** [comment]
regardless of the effort estimate I want to be assigned to this task

**Comment by heliomar-pena** [comment]
You're already assigned @arodriguezl9302 . Thanks for the help!

**Comment by arodriguezl9302** [comment]
One question, I added the 404 page, is that when the route does not exist, it redirects to it, but this 50x error, when does it redirect to this url?

**Comment by Israel-Laguan** [comment]
> One question, I added the 404 page, is that when the route does not exist, it redirects to it, but this 50x error, when does it redirect to this url?

The idea is to send the user programmatically, for example in a trycatch when a user steps in a fatal error, instead of just crash the app, we can send the user to this page, for example using:

`history.push(/internal-error)`

**Comment by arodriguezl9302** [comment]
yes i did the same, tanks
